mybatis:
  mapper-locations: classpath:mapper/*Dao.xml
  type-aliases-package: com.zhangchun.history.consumer.model
  configuration:
    map-underscore-to-camel-case: true
#showSql
logging:
  level:
    com:
      example:
        mapper : debug
server:
  port: 8082
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka
#  instance:
#    prefer-ip-address: true
#    ip-address: 127.0.0.1
#    lease-renewal-interval-in-seconds: 5      # 心跳时间
#    lease-expiration-duration-in-seconds: 10  # 发呆时间，即服务续约到期时间