server:
  port: 10010
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${server.port}
    prefer-ip-address: true
info:
  app.name: cloud-history
  company.name: www.zhangchun.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
spring:
  application:
    name: cloud-gateway