server:
  port: 8085
spring:
  application:
    name: cloud-history-page
  thymeleaf:
    cache: false
  redis:
    host: 192.168.203.132
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/kafka
    username: root
    password: zc123123
    driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
      host: 192.168.203.132
mybatis:
  mapper-locations: classpath:mapper/*Dao.xml
  type-aliases-package: com.zhangchun.history.page.model
  configuration:
    map-underscore-to-camel-case: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 5      # 心跳时间
    lease-expiration-duration-in-seconds: 10  # 发呆时间，即服务续约到期时间

