spring:
  application:
    name: cloud-expire-monitor
  redis:
    host: 192.168.203.132
server:
  port: 8087
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 5      # 心跳时间
    lease-expiration-duration-in-seconds: 10  # 发呆时间，即服务续约到期时间
